---
title: "Relevance of Predictor Variables"
output: html_notebook
---


# Disclaimer


# Example Regression Dataset

The data set contains two variables `Breast Circumference` (BC) and `Body Weight` (BW) where the latter is the response. 

```{r}
suppressPackageStartupMessages( require(dplyr) )
tbl_reg <- tibble::tibble(`Breast Circumference` = c(176, 177, 178, 179, 179, 180, 181, 182,183, 184),
                          `Body Weight` = c(471, 463, 481, 470, 496, 491, 518, 511, 510, 541))
n_nr_ani <- nrow(tbl_reg)
tbl_reg <- bind_cols(tibble::tibble(Animal = 1:n_nr_ani),
                     tbl_reg)
knitr::kable(tbl_reg)
```


# Relevance of Predictors
Create a random predictor which would have no relevance.

```{r}
vec_randpred <- runif(n_nr_ani, 
                      min = min(tbl_reg$`Breast Circumference`), 
                      max = max(tbl_reg$`Breast Circumference`))
tbl_reg_aug <- bind_cols(tbl_reg, tibble(RandPred = round(vec_randpred, digits = 0)))
tbl_reg_aug
```

What does the plot look like

```{r}
# plot(tbl_reg_aug$RandPred, tbl_reg_aug$`Body Weight`)
require(ggplot2)
qplot(tbl_reg_aug$RandPred, tbl_reg_aug$`Body Weight`)
```

As opposed to 

```{r}
plot(tbl_reg_aug$`Breast Circumference`, tbl_reg_aug$`Body Weight`)
```


# Prediction
Leave one out cross validation

```{r}
library(caret)
data <- tibble::tibble(x = rnorm(1000, 3, 2), y = 2*x + rnorm(1000))
train(y ~ x, method = "lm", data = data, trControl = trainControl(method = "LOOCV"))
```

```{r}
train(`Body Weight` ~ `Breast Circumference` + RandPred, method = "lm", data = tbl_reg_aug, trControl = trainControl(method = "LOOCV"))
```

```{r}
train(`Body Weight` ~ `Breast Circumference`, method = "lm", data = tbl_reg_aug, trControl = trainControl(method = "LOOCV"))
```

